### ISSUE TITLE
Error while getting annotations from PRS-T1

### ISSUE THREAD

**Issue by entodoays** [sleidig/calibre_annotations_sonyreader#1]
When I try to get annotations from my Sony PRS-T1 I'm getting the following error:
```
calibre, version 5.10.1
ERROR: Unhandled exception: <b>AttributeError</b>:'dict' object has no attribute 'iterkeys'

calibre 5.10.1  embedded-python: True is64bit: True
Linux-5.8.0-41-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-41-generic', '#46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021')
Python 3.8.5
Interface language: en_GB
Successfully initialized third party plugins: Annotations (1, 14, 0)
Traceback (most recent call last):
  File "calibre_plugins.annotations.action", line 364, in fetch_usb_connected_device_annotations
    self.fetch_usb_device_annotations(primary_name)
  File "calibre_plugins.annotations.action", line 392, in fetch_usb_device_annotations
    annotated_book_list = self.get_annotated_books_on_usb_device(reader_app)
  File "calibre_plugins.annotations.action", line 598, in get_annotated_books_on_usb_device
    ra.get_active_annotations()
  File "/home/chris/Apps/AnnotationsFeching_SonyReader.py", line 164, in get_active_annotations
    for timestamp in sorted(dict_of_anns.iterkeys()):
AttributeError: 'dict' object has no attribute 'iterkeys'
```

**Comment by sleidig** [comment]
Sorry, I haven't looked at this in a while. Great to see somebody using it but I think I won't get around debugging it the next months ...
